/*
PRISMA
Datos adicionales para demostración
Archivo: 12_demo_data.sql
*/

---------------------------------------------------------
-- PACIENTES ADICIONALES
---------------------------------------------------------

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Daniel','Rodriguez',DATE '1988-04-12','M','8888-1004','daniel.rodriguez@correo.com','San Jose','1-0888-1004');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Sofia','Vargas',DATE '1995-09-23','F','8888-1005','sofia.vargas@correo.com','Heredia','1-0995-1005');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Andres','Jimenez',DATE '1979-02-14','M','8888-1006','andres.jimenez@correo.com','Alajuela','2-0779-1006');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Valeria','Castro',DATE '2001-06-30','F','8888-1007','valeria.castro@correo.com','Cartago','3-1001-1007');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Sebastian','Mora',DATE '1992-11-08','M','8888-1008','sebastian.mora@correo.com','Escazu','1-0992-1008');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Camila','Rojas',DATE '1985-03-17','F','8888-1009','camila.rojas@correo.com','Desamparados','1-0885-1009');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Diego','Sanchez',DATE '1975-07-21','M','8888-1010','diego.sanchez@correo.com','Moravia','1-0775-1010');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Natalia','Chaves',DATE '1998-12-05','F','8888-1011','natalia.chaves@correo.com','Curridabat','1-0998-1011');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Alejandro','Solano',DATE '1982-05-19','M','8888-1012','alejandro.solano@correo.com','Tibas','1-0882-1012');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Fernanda','Herrera',DATE '1990-10-10','F','8888-1013','fernanda.herrera@correo.com','Santa Ana','1-0990-1013');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Gabriel','Ramirez',DATE '1968-01-28','M','8888-1014','gabriel.ramirez@correo.com','Heredia','4-0668-1014');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Isabella','Alvarado',DATE '2003-08-15','F','8888-1015','isabella.alvarado@correo.com','Alajuela','2-1003-1015');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Marco','Quesada',DATE '1987-04-03','M','8888-1016','marco.quesada@correo.com','Cartago','3-0887-1016');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Daniela','Araya',DATE '1996-02-25','F','8888-1017','daniela.araya@correo.com','San Jose','1-0996-1017');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Esteban','Mendez',DATE '1980-09-09','M','8888-1018','esteban.mendez@correo.com','Heredia','4-0880-1018');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Laura','Campos',DATE '1993-07-14','F','8888-1019','laura.campos@correo.com','Alajuela','2-0993-1019');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Ricardo','Vega',DATE '1972-12-11','M','8888-1020','ricardo.vega@correo.com','San Jose','1-0772-1020');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Paula','Navarro',DATE '2000-05-06','F','8888-1021','paula.navarro@correo.com','Cartago','3-1000-1021');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Jorge','Brenes',DATE '1984-06-18','M','8888-1022','jorge.brenes@correo.com','Heredia','4-0884-1022');

INSERT INTO PACIENTE
(NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, TELEFONO, CORREO, DIRECCION, CEDULA)
VALUES
('Monica','Salazar',DATE '1991-03-29','F','8888-1023','monica.salazar@correo.com','San Jose','1-0991-1023');

---------------------------------------------------------
-- HISTORIAL PARA CADA PACIENTE NUEVO
---------------------------------------------------------

INSERT INTO HISTORIAL_CLINICO (ID_PACIENTE,FECHA_CREACION,OBSERVACIONES_GENERALES)
SELECT ID_PACIENTE, SYSDATE, 'Historial clínico activo.'
FROM PACIENTE
WHERE ID_PACIENTE > 3
AND NOT EXISTS (
    SELECT 1
    FROM HISTORIAL_CLINICO H
    WHERE H.ID_PACIENTE = PACIENTE.ID_PACIENTE
);

---------------------------------------------------------
-- CITAS HISTORICAS
---------------------------------------------------------

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
SELECT ID_PACIENTE,1,1,SYSDATE-30,'08:00','ATENDIDA','Control médico general'
FROM PACIENTE
WHERE ID_PACIENTE BETWEEN 4 AND 8;

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
SELECT ID_PACIENTE,2,2,SYSDATE-20,'09:00','ATENDIDA','Valoración cardiovascular'
FROM PACIENTE
WHERE ID_PACIENTE BETWEEN 9 AND 13;

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
SELECT ID_PACIENTE,3,3,SYSDATE-10,'10:00','ATENDIDA','Consulta de seguimiento'
FROM PACIENTE
WHERE ID_PACIENTE BETWEEN 14 AND 18;

---------------------------------------------------------
-- CITAS DEL DIA DE LA EXPO
---------------------------------------------------------

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
VALUES (4,1,1,TRUNC(SYSDATE),'08:00','CONFIRMADA','Control general');

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
VALUES (5,2,2,TRUNC(SYSDATE),'09:00','CONFIRMADA','Control cardiológico');

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
VALUES (6,3,3,TRUNC(SYSDATE),'10:00','PROGRAMADA','Consulta de seguimiento');

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
VALUES (7,1,1,TRUNC(SYSDATE),'11:00','PROGRAMADA','Chequeo preventivo');

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
VALUES (8,2,2,TRUNC(SYSDATE),'13:00','CONFIRMADA','Valoración médica');

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
VALUES (9,3,3,TRUNC(SYSDATE),'14:00','PROGRAMADA','Control clínico');

---------------------------------------------------------
-- CITAS FUTURAS
---------------------------------------------------------

INSERT INTO CITA
(ID_PACIENTE,ID_MEDICO,ID_CONSULTORIO,FECHA,HORA,ESTADO,MOTIVO)
SELECT ID_PACIENTE,
       MOD(ID_PACIENTE,3)+1,
       MOD(ID_PACIENTE,3)+1,
       TRUNC(SYSDATE) + MOD(ID_PACIENTE,7)+1,
       '15:00',
       'PROGRAMADA',
       'Cita de seguimiento'
FROM PACIENTE
WHERE ID_PACIENTE BETWEEN 10 AND 23;

---------------------------------------------------------
-- INDICADORES DE SALUD
---------------------------------------------------------

INSERT INTO INDICADOR_SALUD
(ID_PACIENTE,TIPO_INDICADOR,VALOR,UNIDAD_MEDIDA,FECHA_REGISTRO)
SELECT ID_PACIENTE,
       'Peso',
       55 + MOD(ID_PACIENTE * 3,35),
       'kg',
       SYSDATE
FROM PACIENTE
WHERE ID_PACIENTE > 3;

INSERT INTO INDICADOR_SALUD
(ID_PACIENTE,TIPO_INDICADOR,VALOR,UNIDAD_MEDIDA,FECHA_REGISTRO)
SELECT ID_PACIENTE,
       'Frecuencia Cardiaca',
       65 + MOD(ID_PACIENTE,20),
       'lpm',
       SYSDATE
FROM PACIENTE
WHERE ID_PACIENTE > 3;

---------------------------------------------------------
-- ALERGIAS
---------------------------------------------------------

INSERT INTO ALERGIA
(ID_PACIENTE,NOMBRE_ALERGIA,TIPO,SEVERIDAD)
VALUES (5,'Polen','Ambiental','LEVE');

INSERT INTO ALERGIA
(ID_PACIENTE,NOMBRE_ALERGIA,TIPO,SEVERIDAD)
VALUES (7,'Ibuprofeno','Medicamento','MODERADA');

INSERT INTO ALERGIA
(ID_PACIENTE,NOMBRE_ALERGIA,TIPO,SEVERIDAD)
VALUES (10,'Mariscos','Alimentaria','GRAVE');

INSERT INTO ALERGIA
(ID_PACIENTE,NOMBRE_ALERGIA,TIPO,SEVERIDAD)
VALUES (14,'Lactosa','Alimentaria','MODERADA');

INSERT INTO ALERGIA
(ID_PACIENTE,NOMBRE_ALERGIA,TIPO,SEVERIDAD)
VALUES (18,'Polvo','Ambiental','LEVE');

---------------------------------------------------------
-- ANTECEDENTES
---------------------------------------------------------

INSERT INTO ANTECEDENTE_MEDICO
(ID_PACIENTE,TIPO,DESCRIPCION,FECHA_REGISTRO)
VALUES (6,'Cronico','Hipertensión arterial',SYSDATE-365);

INSERT INTO ANTECEDENTE_MEDICO
(ID_PACIENTE,TIPO,DESCRIPCION,FECHA_REGISTRO)
VALUES (9,'Familiar','Antecedentes de diabetes',SYSDATE-500);

INSERT INTO ANTECEDENTE_MEDICO
(ID_PACIENTE,TIPO,DESCRIPCION,FECHA_REGISTRO)
VALUES (12,'Quirurgico','Cirugía de rodilla',SYSDATE-700);

INSERT INTO ANTECEDENTE_MEDICO
(ID_PACIENTE,TIPO,DESCRIPCION,FECHA_REGISTRO)
VALUES (16,'Cronico','Asma controlada',SYSDATE-400);

INSERT INTO ANTECEDENTE_MEDICO
(ID_PACIENTE,TIPO,DESCRIPCION,FECHA_REGISTRO)
VALUES (20,'Familiar','Antecedentes cardiovasculares',SYSDATE-600);

COMMIT;

---------------------------------------------------------
-- RESUMEN
---------------------------------------------------------

SELECT 'Pacientes' AS MODULO, COUNT(*) AS TOTAL FROM PACIENTE
UNION ALL
SELECT 'Medicos', COUNT(*) FROM DOCTOR
UNION ALL
SELECT 'Citas', COUNT(*) FROM CITA
UNION ALL
SELECT 'Consultas', COUNT(*) FROM CONSULTA
UNION ALL
SELECT 'Tratamientos', COUNT(*) FROM TRATAMIENTO
UNION ALL
SELECT 'Indicadores', COUNT(*) FROM INDICADOR_SALUD;

PROMPT ================================================
PROMPT DATOS DE DEMOSTRACION CARGADOS CORRECTAMENTE
PROMPT ================================================